
# 端口号
server:
  port: 8081
mybatis:
  # xml 映射地址
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.qiqi.member_management.management.business.model
  configuration:
    # null值处理
    jdbc-type-for-null: null
# spring 相关配置
spring:
  # 数据源
  datasource:
    # 使用alibaba的druid数据源
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      # 数据库改成自己的 小傻子  如果启动报错的话，把 serverTimezone=GMT%2B8& 去掉
      url: jdbc:mysql://127.0.0.1:3306/member_management?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      # 数据库连接池的一些配置
      initial-size: 5  # 初始化连接池大小
      min-idle: 5      # 最小空闲连接数
      max-active: 5 #最大活跃数
      max-wait: 30000  # 最长等待时间
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 下面是一些监控信息(这druid特色)
      #  配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: com.qiqi.member_management.management.business.*
      # web-stat-filter 配置()
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      # StatViewServlet配置(这是实际访问的 http://localhost:8081/druid/*)
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
      filter:
        stat:
          log-slow-sql: true
# 打印sql日志
logging:
  level:
    com.qiqi.member_management.management.business.mapper: debug

    

